<a href="https://colab.research.google.com/github/Papa-Panda/Paper_reading/blob/main/reinforcementlearning_value_based.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import gymnasium as gym
import numpy as np
import torch
from collections import defaultdict

import torch.nn as nn
import torch.optim as optim

In [ ]:
# Create the environment
env = gym.make("FrozenLake-v1", is_slippery=False)  # deterministic version

# Define parameters
num_episodes = 5000
gamma = 0.99  # discount factor
learning_rate = 0.1
alpha = 0.1  # learning rate

state_size = env.observation_space.n

In [ ]:
# Monte Carlo

In [ ]:
# Initialize value function as torch tensor
value_table = torch.zeros(state_size, dtype=torch.float32)

# Helper: generate an episode
def generate_episode(env):
    episode = []
    state, _ = env.reset()
    done = False
    while not done:
        action = env.action_space.sample()  # random policy
        next_state, reward, terminated, truncated, _ = env.step(action)
        done = terminated or truncated
        episode.append((state, action, reward))
        state = next_state
    return episode

# Monte Carlo Prediction
returns_sum = defaultdict(float)
returns_count = defaultdict(int)

for episode_idx in range(num_episodes):
    episode = generate_episode(env)
    visited_states = set()
    G = 0
    for t in reversed(range(len(episode))):
        state, action, reward = episode[t]
        G = gamma * G + reward
        if state not in visited_states:
            visited_states.add(state)
            returns_sum[state] += G
            returns_count[state] += 1
            value_table[state] = returns_sum[state] / returns_count[state]

# Print the learned value function
print("Learned Value Function (state-values):")
for s in range(state_size):
    print(f"State {s}: {value_table[s].item():.3f}")


Learned Value Function (state-values):
State 0: 0.017
State 1: 0.016
State 2: 0.032
State 3: 0.015
State 4: 0.018
State 5: 0.000
State 6: 0.066
State 7: 0.000
State 8: 0.039
State 9: 0.107
State 10: 0.198
State 11: 0.000
State 12: 0.000
State 13: 0.258
State 14: 0.514
State 15: 0.000


In [ ]:
# TD learning

In [ ]:
# Initialize value function as torch tensor
value_table = torch.zeros(state_size, dtype=torch.float32)
# Value function (as a torch tensor)
state_size = env.observation_space.n
value_table = torch.zeros(state_size, dtype=torch.float32)

for episode in range(num_episodes):
    state, _ = env.reset()
    done = False

    while not done:
        action = env.action_space.sample()  # random policy
        next_state, reward, terminated, truncated, _ = env.step(action)
        done = terminated or truncated

        # TD(0) update rule: V(s) ← V(s) + α [R + γ * V(s') - V(s)]
        td_target = reward + gamma * value_table[next_state]
        td_error = td_target - value_table[state]
        value_table[state] += alpha * td_error

        state = next_state

# Print the learned value function
print("Learned Value Function (TD):")
for s in range(state_size):
    print(f"State {s}: {value_table[s].item():.3f}")

Learned Value Function (TD):
State 0: 0.007
State 1: 0.005
State 2: 0.008
State 3: 0.006
State 4: 0.010
State 5: 0.000
State 6: 0.011
State 7: 0.000
State 8: 0.025
State 9: 0.051
State 10: 0.094
State 11: 0.000
State 12: 0.000
State 13: 0.098
State 14: 0.205
State 15: 0.000


In [ ]:
# TD learning: neural network

In [ ]:
# One-hot encoding for discrete states
def one_hot(state, num_states):
    vec = torch.zeros(num_states, dtype=torch.float32)
    vec[state] = 1.0
    return vec

# Define the value network
class ValueNetwork(nn.Module):
    def __init__(self, input_size):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(input_size, 32),
            nn.ReLU(),
            nn.Linear(32, 1)  # Output: V(s)
        )

    def forward(self, x):
        return self.net(x)

# Initialize network and optimizer
value_net = ValueNetwork(state_size)
optimizer = optim.Adam(value_net.parameters(), lr=0.01)

for episode in range(num_episodes):
    state, _ = env.reset()
    done = False

    while not done:
        action = env.action_space.sample()  # random policy
        next_state, reward, terminated, truncated, _ = env.step(action)
        done = terminated or truncated

        # Prepare inputs
        s = one_hot(state, state_size)
        s_next = one_hot(next_state, state_size)

        # Compute TD target: R + γ * V(s')
        with torch.no_grad():
            target = reward + gamma * value_net(s_next)

        # Prediction and loss
        prediction = value_net(s)
        loss = nn.functional.mse_loss(prediction, target)

        # Backpropagation
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        state = next_state

# Show learned value estimates
print("State-Value Estimates (using neural network):")
for s in range(state_size):
    v = value_net(one_hot(s, state_size)).item()
    print(f"State {s}: {v:.3f}")

State-Value Estimates (using neural network):
State 0: 0.008
State 1: 0.007
State 2: 0.013
State 3: 0.021
State 4: 0.008
State 5: -0.008
State 6: 0.009
State 7: 0.035
State 8: 0.019
State 9: -0.002
State 10: -0.014
State 11: -0.008
State 12: 0.037
State 13: -0.003
State 14: -0.040
State 15: 0.006


TD learning: sarsa algorithm

In [ ]:
import gymnasium as gym
import numpy as np

# Create environment
env = gym.make("FrozenLake-v1", is_slippery=False)  # deterministic for easier learning
n_states = env.observation_space.n
n_actions = env.action_space.n

# Initialize Q-table
Q = np.zeros((n_states, n_actions))
alpha = 0.1       # learning rate
gamma = 0.99      # discount factor
epsilon = 0.1     # exploration rate

# Epsilon-greedy policy
def epsilon_greedy(state, Q, epsilon):
    if np.random.rand() < epsilon:
        return np.random.choice(n_actions)
    return np.argmax(Q[state])

# Training loop
num_episodes = 5000
for episode in range(num_episodes):
    state, _ = env.reset()
    action = epsilon_greedy(state, Q, epsilon)
    done = False

    while not done:
        next_state, reward, terminated, truncated, _ = env.step(action)
        done = terminated or truncated
        next_action = epsilon_greedy(next_state, Q, epsilon)

        # SARSA update
        td_target = reward + gamma * Q[next_state, next_action]
        td_error = td_target - Q[state, action]
        Q[state, action] += alpha * td_error

        state = next_state
        action = next_action

# Print the learned Q-values
print("Learned Q-values (SARSA):")
print(Q)

# Derive policy
policy = np.argmax(Q, axis=1)
print("Derived policy:")
print(policy.reshape((4, 4)))  # 4x4 grid for FrozenLake

Learned Q-values (SARSA):
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Derived policy:
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


TD learning: sarsa neural network version

In [1]:
import gymnasium as gym
import torch
import torch.nn as nn
import torch.optim as optim
import random
import numpy as np

# Set up environment
env = gym.make("CartPole-v1")
state_dim = env.observation_space.shape[0]
action_dim = env.action_space.n

# Q-network
class QNetwork(nn.Module):
    def __init__(self, state_dim, action_dim):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(state_dim, 128),
            nn.ReLU(),
            nn.Linear(128, action_dim)
        )

    def forward(self, x):
        return self.net(x)

# Initialize network and optimizer
q_net = QNetwork(state_dim, action_dim)
optimizer = optim.Adam(q_net.parameters(), lr=1e-3)
loss_fn = nn.MSELoss()

# Hyperparameters
epsilon = 0.1
gamma = 0.99
num_episodes = 500
batch_size = 1  # SARSA is typically updated per step

def select_action(state, epsilon):
    if random.random() < epsilon:
        return random.randint(0, action_dim - 1)
    else:
        with torch.no_grad():
            q_values = q_net(torch.FloatTensor(state))
            return torch.argmax(q_values).item()

# Training loop
for episode in range(num_episodes):
    state, _ = env.reset()
    action = select_action(state, epsilon)
    done = False
    total_reward = 0

    while not done:
        next_state, reward, terminated, truncated, _ = env.step(action)
        done = terminated or truncated
        next_action = select_action(next_state, epsilon)

        # Compute target using SARSA formula
        q_values_next = q_net(torch.FloatTensor(next_state))
        target = reward + (gamma * q_values_next[next_action].item() * (not done))

        # Predicted Q(s, a)
        q_values = q_net(torch.FloatTensor(state))
        predicted = q_values[action]

        loss = loss_fn(predicted, torch.tensor(target))

        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        state = next_state
        action = next_action
        total_reward += reward

    if episode % 50 == 0:
        print(f"Episode {episode}, Total Reward: {total_reward}")

env.close()


Episode 0, Total Reward: 10.0
Episode 50, Total Reward: 9.0
Episode 100, Total Reward: 10.0
Episode 150, Total Reward: 15.0
Episode 200, Total Reward: 14.0
Episode 250, Total Reward: 49.0
Episode 300, Total Reward: 28.0
Episode 350, Total Reward: 48.0
Episode 400, Total Reward: 32.0
Episode 450, Total Reward: 71.0
